create table if not exists public.users
(
    creation_date      date,
    id                 bigint generated by default as identity
        primary key,
    driving_license_id varchar(255),
    email              varchar(255),
    firstname          varchar(255),
    lastname           varchar(255),
    passport_id        varchar(255),
    phone_number       varchar(255)
);

alter table public.users
    owner to postgres;

create table if not exists public.car
(
    id                 bigint generated by default as identity
        primary key,
    brand              varchar(255) not null,
    model              varchar(255) not null,
    year_of_production date         not null,
    plate_number       varchar(255) not null
        unique,
    is_available       boolean default false,
    daily_fee          numeric(38, 2),
    user_id            bigint
        constraint fkc2osr9qmb46vr8pjyps6weii0
            references public.users
);

alter table public.car
    owner to postgres;

create table if not exists public.payment
(
    id             bigint not null
        primary key,
    user_id        bigint
        references public.users,
    session_id     bigint,
    status         varchar(255),
    url            varchar(255),
    payment_amount numeric(38, 2),
    type           varchar(255),
    payment_date   date
);

alter table public.payment
    owner to postgres;

create table if not exists public.booking
(
    id              bigint not null
        primary key,
    user_id         bigint
        references public.users,
    car_id          bigint
        references public.car,
    start_date_time date,
    end_date_time   date,
    status          varchar(255)
);

alter table public.booking
    owner to postgres;

insert into users (creation_date, driving_license_id, email, firstname, lastname, passport_id, phone_number) values
                                                                                                                 ('2024-04-04', 'AB12354C', 'u@mail.ru', 'u', 's', 'KB2315432', '+375296583945'),
                                                                                                                 ('2024-07-07', 'ED32451R', 't@mail.ru', 'e', 'r', 'KB2350996', '+375448493200'),
                                                                                                                 ('2024-06-06', 'TY39560T', 'r@mail.ru', 'w', 's', 'KB6950432', '+375295406873'),
                                                                                                                 ('2023-10-10', 'TK57860R', 's@mail.ru', 'i', 'c', 'KB1482086', '+375448321594'),
                                                                                                                 ('2023-12-06', 'OA14512I', 'd@mail.ru', 'y', 'o', 'KB4562340', '+375291232349')
;

insert into car (brand, model, year_of_production, plate_number, daily_fee, user_id) values
                                                                                         ('Toyota', 'Corolla', '2020-04-04', 'AB345623', 50.0, 1),
                                                                                         ('Nissan', 'Quasqai', '2021-05-05', 'AC347623', 60.0, 2),
                                                                                         ('Audi', 'Quattro', '2022-04-04', 'AD367623', 70.0, 3),
                                                                                         ('Mercedes-Benz', 'CLS', '2023-06-06', 'AE945693', 80.0, 4),
                                                                                         ('BMW', 'X5', '2020-04-04', 'AW045023', 90.0, 5)
;

insert into payment (id, user_id, session_id, status, url, payment_amount, type, payment_date)  values
                                                                                                    ('1', '1', '1', 'Accepted', 'http://localhost', 50.0, 'Mastercard', '2024-04-04'),
                                                                                                    ('2', '2', '2', 'Accepted', 'http://localhost', 60.0, 'Mastercard', '2023-05-06'),
                                                                                                    ('3', '3', '3', 'Accepted', 'http://localhost', 70.0, 'Visa', '2022-03-07'),
                                                                                                    ('4', '4', '4', 'Declined', 'http://localhost', 80.0, 'Visa', '2021-02-05'),
                                                                                                    ('5', '5', '5', 'Accepted', 'http://localhost', 90.0, 'Mastercard', '2024-03-03')
;

insert into booking (id, user_id, car_id, start_date_time, end_date_time, status) values
                                                                                      ('1', '1', '1', '2020-04-04', '2020-04-04', 'Finished'),
                                                                                      ('2', '2', '2', '2021-04-04', '2021-04-05', 'Finished'),
                                                                                      ('3', '3', '3', '2022-04-04', '2022-04-06', 'Finished'),
                                                                                      ('4', '4', '4', '2023-04-04', '2023-04-04', 'Finished'),
                                                                                      ('5', '5', '5', '2024-08-01', '2024-07-01', 'Running')


